### PR TITLE
Update Namespace

### PR DESCRIPTION
**Pull request by QuanWanxx**
Update code namespace from **Microsoft.Health.Fhir.Synapse...** to **Microsoft.Health.AnalyticsConnector...**

### CODE REVIEW

**Review by hongyh13 — COMMENTED** [review]
Will we have another pr to re-org the folder structure?

**Comment by QuanWanxx** [comment]
> Will we have another pr to re-org the folder structure?

Yes, I plan to use another PR to re-org the Job modules.

**Review by hongyh13 — APPROVED** [review]
maybe we need to run tool and azure function e2e tests to make sure it works.

**Comment by QuanWanxx** [comment]
> maybe we need to run tool and azure function e2e tests to make sure it works.

Thanks for reminding, I will run our overall CI test using another branch, and merge this after the tests are finished.

**Pull request merged**
