### PR TITLE
upgrade to net6.0

### PR DESCRIPTION
**Pull request by hongyh13**
upgrade from net5.0 to net6.0

### CODE REVIEW

**Comment by moria97** [comment]
We may need to use [windows-latest/windows-2022](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml) image in CI agents for .net 6.0 suport. Specially, there are no azure storage emulator in windws-2022, you may need to run emulator like [this](https://github.com/microsoft/FHIR-Analytics-Pipelines/blob/79f9421fda84095084a62745be3a3942dfa4e1be/FhirToDataLake/azurepipelines/ci.yml#L27)

**Comment by moria97** [comment]
I'm afraid we also need to upgrade the azure function code for .net 6 support, too

**Comment by hongyh13** [comment]
> 

Thanks for the comments, fixed it now.

**Comment by moria97** [comment]
Can we check whether the azure function still works for .NET 6? There is no e2e tests for the FunctionApp code.

**Comment by hongyh13** [comment]
> Can we check whether the azure function still works for .NET 6? There is no e2e tests for the FunctionApp code.

Sure, I ran the azure function app on my local machine, and in the published azure function app, they both ran correctly.

**Review by moria97 — APPROVED** [review]
:shipit:

**Pull request merged**
